## 11.2 예외 처리 코드
- 💠 **예외 처리 코드** : 예외가 발생했을 때 프로그램의 갑작스러운 종료를 막고 정상 실행을 유지할 수 있도록 처리하는 코드
- `try-catch-finally` 블록으로 구성됨.
- try 블록에서
  - 예외 없이 정상 실행되면 ➡️ catch 블록은 실행되지 않고 finally 블록이 실행됨.
  - 예외가 발생하면 ➡️ catch 블록이 실행되고 연이어 finally 블록이 실행됨.
- 예외 발생 여부와 상관없이 finally 블록은 **항상** 실행됨.
  - try 블록과 catch 블록에서 return 문을 사용하더라도 finally 블록은 항상 실행됨.
  - finally 블록은 옵션으로 생각 가능.
- 예시 코드
  ```java
  public static void printLength(String data) {
    try {
     int result = data.length();
     System.out.println("문자 수: " + result);
    } catch(NullPointerException e) {
      System.out.println(e.getMessage());    
    } finally {
      System.out.println("마무리 실행");
    }    
  }
  ```
### 예외 정보를 얻는 방법
- `System.out.println(e.getMessage());`
  - 예외가 발생한 이유만 출력
  ```java
  Cannot invoke "String.length()" because "data" is null
  ```
- `System.out.println(e.toString());`
  - 예외의 종류와 예외가 발생한 이유 출력
  ```java
  java.lang.NullPointerException: Cannot invoke "String.length()" because "data" is null
  ```
- `e.printStackTrace();`
  - 예외의 종류, 예외가 발생한 이유와 예외가 어디서 발생했는지 추적한 내용까지 출력
  ```java
  java.lang.NullPointerException: Cannot invoke "String.length()" because "data" is null
    at ch11.sec02.exam01.ExceptionHandlingExample2.printLength(ExceptionHandlingExample2.java:6))
    at ...
  ```
### 🙋 면접 예상 질문
- 예외 처리 코드는 어떻게 구성되는지 설명해주세요.